poses:
  Sleep:
    waist: 0.0
    shoulder: -1.8799999952316284
    elbow: 1.5
    wrist_angle: 0.800000011920929
    wrist_rotate: 0.0
  Home:
    waist: 0.0
    shoulder: -1.8799999952316284
    elbow: 1.5
    wrist_angle: 0.800000011920929
    wrist_rotate: 0.0
  p1:
    waist: 0.0
    shoulder: -1.88
    elbow: 1.5
    wrist_angle: 0.8
    wrist_rotate: 0.0
  p2:
    waist: 0.0
    shoulder: -1.88
    elbow: 1.5
    wrist_angle: 0.8
    wrist_rotate: 0.0
