poses:
  ros__parameters:
    targets:
      Home:
        waist: 0.0
        shoulder: 0.0
        elbow: 0.0
        wrist_angle: 0.0
        wrist_rotate: 0.0
        gripper: 0.0
        left_finger: 0.019493588689617928
        right_finger: -0.019493588689617928
      Sleep:
        waist: 0.0
        shoulder: -1.8799999952316284
        elbow: 1.5
        wrist_angle: 0.800000011920929
        wrist_rotate: 0.0
        gripper: 0.0
        left_finger: 0.019493588689617928
        right_finger: -0.019493588689617928
