moveit_controllers:
  traj: arm_controller
  gripper_traj: gripper_controller
  gripper_action: /wx200/gripper_pwm_bridge/gripper_cmd
  gripper_max_effort: 0.0

joints:
  arm_joints:
    - waist
    - shoulder
    - elbow
    - wrist_angle
    - wrist_rotate
  gripper_joints:
    - left_finger

poses:
  home: [0.0, 0.0, 0.0, 0.0, 0.0]
  holdup: [0.0, -1.0, 1.0, 0.0, 0.0]
  Sleep: [0.0, -1.88, 1.55, 0.8, 0.0]
  Release: [-0.14419420063495636, 0.21475732326507568, -0.37582531571388245, 0.2485048919916153, 0.04295146465301514]